name: Latest blog post workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [blog-page-updated]
  workflow_dispatch: 
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Blog Post Workflow
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          feed_list: "https://blog.ch3nyang.top/feed.xml"
          date_format: yyyy - mmm
          template: <p><a href= $url >$date - $title</a></p>
        
