name: Latest blog post workflow
on:
  schedule:
    - cron: '05 16 * * *'
  workflow_dispatch: 
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          feed_list: "https://wcy-dt.github.io/feed.xml"
          date_format: mmm d, yyyy
          template: <p align="center"><a href= $url > $title - $date </a></p><br/>
        
